### ISSUE TITLE
Update for compatibility with hapi 14.x.x

### ISSUE THREAD

**Issue by brightloudnoise** [felixheck/wurst#4]
The package.json is currently locked to hapi 13.x.x

I tried using it with hapi 14.x.x and while the routes are mounted, I am seeing some odd behaviour. (This is on Windows 8.1)

Using folders to organize routes is not reflected in the path:

e.g. [foo]/bar is being mounted at /bar

Also when logging is enabled, I only see the following:

"Object prefixed the following routes", and no routes are listed.

I've included the [breaking changes  for hapi 14.x.x which appear to be limited to Joi](https://github.com/hapijs/hapi/issues/3272)

**Comment by brightloudnoise** [comment]
The mounting and logging issue I found on Windows is due to an error in getPathTree.  path.sep = '\' on win32, but getPathTree being passed a path assembled with forward slashes from glob.

```
 getPathTree: function getPathTree(filePath) {
    var splitPath = filePath.split(**path.sep**);
    splitPath.pop();

    return splitPath;
  },
```

Changing it to just use a forward slash corrected the issue.
```
    var splitPath = filePath.split('/');
```

**Comment by felixheck** [comment]
@brightloudnoise thanks – it's merged and will published in a few minutes!
